app = "together"
primary_region = "ams"

[build]

[env]
  DATABASE_URL = "sqlite:////data/db.sqlite"
  UPLOADS_DIR = "/data/uploads"
  DEBUG = "false"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
